### ISSUE TITLE
Unable to build tempto

### ISSUE THREAD

**Issue by anusudarsan** [prestodb/tempto#39] opened 2015-08-28 14:01 UTC
I am trying to build tempto using the command : ./gradlew install -x signArchives

I get the following error:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/anu/workspace/tempto/build.gradle' line: 161

* What went wrong:
A problem occurred evaluating root project 'tempto'.
> No such property: nexusUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Any ideas?

**Comment by sogorkis** [comment] 2015-08-28 14:06
This seems to be duplicate of: #34

**Comment by pnowojski** [comment] 2015-08-28 14:08
You probably should specify parameters in gradle.properties file. It is required for publishing to maven central. You can base on gradle.properties.example file. My guess is that you can use blank/random values as long as you don't try to publish artifacts.

**Comment by anusudarsan** [comment] 2015-08-28 15:07
Ok, I added a gradle.properties file with just empty values and build passed. Thanks for the suggestion.

**Comment by losipiuk** [comment] 2015-09-04 11:11
build.properties is no longer required for build.

**Closed by losipiuk** 2015-09-04 11:11 UTC
